import Head from "next/head";
import MenuBar from "./MenuBar";

import styles from "../styles/Home.module.css";

export default function Layout({ title, children }) {
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MenuBar />

      <main className={styles.main}>{children}</main>
    </div>
  );
}
